name: Docker Image Vulnerability Scan

on:
  pull_request:
    paths:
      - 'frontend/Dockerfile'
      - 'backend/Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-image-scan.yml'
  push:
    branches: [main]
    paths:
      - 'frontend/Dockerfile'
      - 'backend/Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-image-scan.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }} image
        run: |
          docker build -t ${{ matrix.service }} ./
            ${{ matrix.service }}

      - name: Scan ${{ matrix.service }} image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: ${{ matrix.service }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
